### ISSUE TITLE
Need favs (likes) and retweets count

### ISSUE THREAD

**Issue by kavir10** [viksit/covidconnect#3]
Hey there, to integrate with https://indiacovidresources.in we need to filter out tweets that are either too low on likes or too high on retweets.

This will make the tweets more relevant to the people who are searching for timely resources.

Thanks for making this API!

**Comment by brainless** [comment]
Hey @viksit if you do not mind I can handle this and open a PR.

**Comment by viksit** [comment]
@brainless yes, please coordinate with #4

**Comment by brainless** [comment]
@kavir10 this has been tackled now. I think we are waiting for deployment. Please close this issue after you check it live (after deployment).
