### ISSUE TITLE
Add a new end point that uses Twitter v1.1 API

### ISSUE THREAD

**Issue by rgxai** [viksit/covidconnect#4]
Create a new end point that uses Twitter v1.1 [API](https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction) and returns data in the same format as it is already being returned

**Comment by viksit** [comment]
Also, @sumitdatta had some changes he wanted to add in (eg, retweets etc). We should coordinate with him too.

**Comment by brainless** [comment]
Hello @rgxai, @viksit can you please tell me what we are trying to achieve with Twitter 1.1 API? Just in case it is already possible with v2 API.

**Comment by rgxai** [comment]
@brainless v1.1 provides us access to 5 queries per second and @viksit has special access to it for our COVID use case. It is not possible with v2.0 as v2.0 has a monthly tweet cap at 500k tweets. Hence we want to migrate to v1.1

**Comment by brainless** [comment]
Hello @rgxai , @viksit,

So @apoorvsingal has been working on this and he discovered that the response structure of Twitter Search API v1.1 and v2 are quite different. So I have propose this for the moment:

1. `/api` - does what it is, Twitter v2 API
2. `/api/1.1` - uses Twitter v1.1 API
3. `/api/2` - explicit use of Twitter v2 API - basically another route to the same controller above

Then in the next task we can add a /api/merge to merge and send all data. But this can be postponed to when people demand it.
