### ISSUE TITLE
Do basic query understanding of tweets and filter into resource_type

### ISSUE THREAD

**Issue by viksit** [viksit/covidconnect#8]
Today, each API call fetches a 100 tweets. 

https://covidconnect.vercel.app/api/1.1/data?city=delhi&resource_type=supply

```"full_text": "@appurv_gupta ❗98716 57154❗\n🔴Empty oxygen cylinders🔴 are available with this person near #Okhla \n#Delhi  #verified personally at 10.50 pm on 1st may.\n10 ltr 14k\n20ltr 25k\n30ltr 38k",```

So far, we're simply showing these as a list of tweets.

Add a filter that takes these 100 tweets, and adds on a parameter to it called `resource_type`.

These can be,

- Oxygen Cylinders
- Oxygen Cannisters
- Medicines [Diff kinds]
- Hospital Beds
- Helplines
- Vaccine sources

This can then be used to filter on the main page of life.corona.network,

![image](https://user-images.githubusercontent.com/198669/116795847-bb553900-aa8c-11eb-97ac-72f41fc9c529.png)

Would also be helpful to extract phone numbers, addresses into structured fields.

**Comment by apoorvsingal** [comment]
Hey! I have a script that does exactly this! It's pretty basic but yea it works: https://replit.com/@ApoorvSingal/tweet-parser. If you could tell me the exact format of data you would like you to have, I should be able to implement it pretty easily.

**Comment by viksit** [comment]
That would be awesome. Just a new key called “cc_resource_type_detail” or something that’s a map. {Type: oxygen, phone: .., other meta}
