### ISSUE TITLE
Allow searching for demand/supply in any city

### ISSUE THREAD

**Issue by brainless** [viksit/covidconnect#9]
Hello everyone,

We want to make possible to search demand/supply data in any city and get all the responses. This helps API consumers who are collecting data at national level and want to separate city themselves. The discussion started inside team of https://covid.army/ but I feel this will be needed by other teams too.

The URL parameter for `city` itself should stay mandatory and accept a value of `any`. This would mean that any API consumer who forgets to use `city` still gets an error and `city=any` is explicit.

The proposal to make the city parameter optional was by @apoorvsingal, thanks.

Thank you

**Comment by viksit** [comment]
Totally, makes sense to me!
